import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class CurrencySelectionScreen extends StatefulWidget {
  final Function onSaved;
  final AppBar? appBar;
  const CurrencySelectionScreen({super.key, required this.onSaved, this.appBar});

  @override
  _CurrencySelectionScreenState createState() =>
      _CurrencySelectionScreenState();
}

class _CurrencySelectionScreenState extends State<CurrencySelectionScreen> {
  String searchValue = '';
  List<Map<String, dynamic>> filteredList = List.from(currencies);

  void onSearchChanged(String value) {
    setState(() {
      searchValue = value.trim().toLowerCase();
      filteredList = currencies
          .where((currency) =>
      currency['name']!.toLowerCase().contains(searchValue) || currency['code']!.toLowerCase().contains(searchValue) ||
          currency['symbol']!.toLowerCase().contains(searchValue))
          .toList();
    });
  }

  void onSaved(Map<String, dynamic> currency) {
    Navigator.pop(context, currency);
    widget.onSaved(currency);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar:widget.appBar?? AppBar(
        backgroundColor: Colors.white,
        title: Text("Select Currency"),
        centerTitle: true,
        leading: GestureDetector(
            onTap: () {
              Navigator.pop(context);
            },
            child: Icon(
              Icons.arrow_back_ios_new_outlined,
              size: 25,
            )),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            TextField(
              onChanged: onSearchChanged,
              decoration: InputDecoration(
                hintText: "Search Currency",
                prefixIcon: Icon(Icons.search, size: 24),
                filled: true,
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(10.0),
                  borderSide: BorderSide.none,
                ),
              ),
            ),
            Expanded(
              child: filteredList.isEmpty
                  ? Center(child: Text("No data found"))
                  : ListView.builder(
                itemCount: filteredList.length,
                itemBuilder: (context, index) {
                  final currency = filteredList[index];
                  return ListTile(
                    onTap: () => onSaved(currency),
                    leading: CachedNetworkImage(
                      imageUrl:
                      "https://flagcdn.com/w40/${currency['flag'][0].toString().toLowerCase()}${currency['flag'][1].toString().toLowerCase()}.png",
                      errorWidget: (context, url, error) =>
                          Icon(Icons.error),
                      width: 30,
                      height: 30,
                    ),
                    title: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(currency['flag']!),
                        Text(currency['symbol']!),
                      ],
                    ),
                    subtitle: Text(currency['name']!),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

List<Map<String, dynamic>> currencies = [
  {
    "code": "PHP",
    "name": "Philippines Peso",
    "symbol": "\u20B1",
    "flag": "PHP",
    "decimal_digits": 2,
    "number": 608,
    "name_plural": "Philippine pesos",
  },
  {
    "code": "USD",
    "name": "United States Dollar",
    "symbol": "\$",
    "flag": "USD",
    "decimal_digits": 2,
    "number": 840,
    "name_plural": "US dollars",
  },
  {
    "code": "EUR",
    "name": "Euro",
    "symbol": "€",
    "flag": "EUR",
    "decimal_digits": 2,
    "number": 978,
    "name_plural": "Euros",
  },
  {
    "code": "JPY",
    "name": "Japanese Yen",
    "symbol": "¥",
    "flag": "JPY",
    "decimal_digits": 0,
    "number": 392,
    "name_plural": "Japanese yen",
  },
  {
    "code": "GBP",
    "name": "British Pound",
    "symbol": "£",
    "flag": "GBP",
    "decimal_digits": 2,
    "number": 826,
    "name_plural": "British pounds sterling",
  },
  {
    "code": "AUD",
    "name": "Australian Dollar",
    "symbol": "\$",
    "flag": "AUD",
    "decimal_digits": 2,
    "number": 36,
    "name_plural": "Australian dollars",
  },
  {
    "code": "CAD",
    "name": "Canadian Dollar",
    "symbol": "\$",
    "flag": "CAD",
    "decimal_digits": 2,
    "number": 124,
    "name_plural": "Canadian dollars",
  },
  {
    "code": "CHF",
    "name": "Switzerland Franc",
    "symbol": "CHF",
    "flag": "CHF",
    "decimal_digits": 2,
    "number": 756,
    "name_plural": "Swiss francs",
  },
  {
    "code": "CNY",
    "name": "China Yuan Renminbi",
    "symbol": "¥",
    "flag": "CNY",
    "decimal_digits": 2,
    "number": 156,
    "name_plural": "Chinese yuan",
  },
  {
    "code": "HKD",
    "name": "Hong Kong Dollar",
    "symbol": "\$",
    "flag": "HKD",
    "decimal_digits": 2,
    "number": 344,
    "name_plural": "Hong Kong dollars",
  },
  {
    "code": "NZD",
    "name": "New Zealand Dollar",
    "symbol": "\$",
    "flag": "NZD",
    "decimal_digits": 2,
    "number": 554,
    "name_plural": "New Zealand dollars",
  },
  {
    "code": "SEK",
    "name": "Sweden Krona",
    "symbol": "kr",
    "flag": "SEK",
    "decimal_digits": 2,
    "number": 752,
    "name_plural": "Swedish kronor",
  },
  {
    "code": "KRW",
    "name": "South Korea Won",
    "symbol": "₩",
    "flag": "KRW",
    "decimal_digits": 0,
    "number": 410,
    "name_plural": "South Korean won",
  },
  {
    "code": "SGD",
    "name": "Singapore Dollar",
    "symbol": "\$",
    "flag": "SGD",
    "decimal_digits": 2,
    "number": 702,
    "name_plural": "Singapore dollars",
  },
  {
    "code": "NOK",
    "name": "Norway Krone",
    "symbol": "kr",
    "flag": "NOK",
    "decimal_digits": 2,
    "number": 578,
    "name_plural": "Norwegian kroner",
  },
  {
    "code": "MXN",
    "name": "Mexico Peso",
    "symbol": "\$",
    "flag": "MXN",
    "decimal_digits": 2,
    "number": 484,
    "name_plural": "Mexican pesos",
  },
  {
    "code": "INR",
    "name": "Indian Rupee",
    "symbol": "₹",
    "flag": "INR",
    "decimal_digits": 2,
    "number": 356,
    "name_plural": "Indian rupees",
  },
  {
    "code": "RUB",
    "name": "Russia Ruble",
    "symbol": "₽",
    "flag": "RUB",
    "decimal_digits": 2,
    "number": 643,
    "name_plural": "Russian rubles",
  },
  {
    "code": "ZAR",
    "name": "South Africa Rand",
    "symbol": "R",
    "flag": "ZAR",
    "decimal_digits": 2,
    "number": 710,
    "name_plural": "South African rand",
  },
  {
    "code": "TRY",
    "name": "Turkish Lira",
    "symbol": "₺",
    "flag": "TRY",
    "decimal_digits": 2,
    "number": 949,
    "name_plural": "Turkish Lira",
  },
  {
    "code": "BRL",
    "name": "Brazilian Real",
    "symbol": "R\$",
    "flag": "BRL",
    "decimal_digits": 2,
    "number": 986,
    "name_plural": "Brazilian Reais",
  },
  {
    "code": "TWD",
    "name": "Taiwan New Dollar",
    "symbol": "NT\$",
    "flag": "TWD",
    "decimal_digits": 2,
    "number": 901,
    "name_plural": "New Taiwan dollars",
  },
  {
    "code": "DKK",
    "name": "Denmark Krone",
    "symbol": "kr",
    "flag": "DKK",
    "decimal_digits": 2,
    "number": 208,
    "name_plural": "Danish kroner",
  },
  {
    "code": "PLN",
    "name": "Poland Zloty",
    "symbol": "zł",
    "flag": "PLN",
    "decimal_digits": 2,
    "number": 985,
    "name_plural": "Polish zlotys",
  },
  {
    "code": "THB",
    "name": "Thailand Baht",
    "symbol": "฿",
    "flag": "THB",
    "decimal_digits": 2,
    "number": 764,
    "name_plural": "Thai baht",
  },
  {
    "code": "IDR",
    "name": "Indonesia Rupiah",
    "symbol": "Rp",
    "flag": "IDR",
    "decimal_digits": 0,
    "number": 360,
    "name_plural": "Indonesian rupiahs",
  },
  {
    "code": "HUF",
    "name": "Hungary Forint",
    "symbol": "Ft",
    "flag": "HUF",
    "decimal_digits": 0,
    "number": 348,
    "name_plural": "Hungarian forints",
  },
  {
    "code": "CZK",
    "name": "Czech Koruna",
    "symbol": "Kč",
    "flag": "CZK",
    "decimal_digits": 2,
    "number": 203,
    "name_plural": "Czech Republic korunas",
  },
  {
    "code": "ILS",
    "name": "Israel Shekel",
    "symbol": "₪",
    "flag": "ILS",
    "decimal_digits": 2,
    "number": 376,
    "name_plural": "Israeli new sheqels",
  },
  {
    "code": "CLP",
    "name": "Chile Peso",
    "symbol": "\$",
    "flag": "CLP",
    "decimal_digits": 0,
    "number": 152,
    "name_plural": "Chilean pesos",
  },
  {
    "code": "AED",
    "name": "Emirati Dirham",
    "symbol": "د.إ",
    "flag": "AED",
    "decimal_digits": 2,
    "number": 784,
    "name_plural": "UAE dirhams",
  },
  {
    "code": "COP",
    "name": "Colombia Peso",
    "symbol": "\$",
    "flag": "COP",
    "decimal_digits": 0,
    "number": 170,
    "name_plural": "Colombian pesos",
  },
  {
    "code": "SAR",
    "name": "Saudi Arabia Riyal",
    "symbol": "﷼",
    "flag": "SAR",
    "decimal_digits": 2,
    "number": 682,
    "name_plural": "Saudi riyals",
  },
  {
    "code": "MYR",
    "name": "Malaysia Ringgit",
    "symbol": "RM",
    "flag": "MYR",
    "decimal_digits": 2,
    "number": 458,
    "name_plural": "Malaysian ringgits",
  },
  {
    "code": "RON",
    "name": "Romania Leu",
    "symbol": "L",
    "flag": "RON",
    "decimal_digits": 2,
    "number": 946,
    "name_plural": "Romanian lei",
  },
  {
    "code": "AFN",
    "name": "Afghanistan Afghani",
    "symbol": "؋",
    "flag": "AFN",
    "decimal_digits": 0,
    "number": 971,
    "name_plural": "Afghan Afghanis",
  },
  {
    "code": "ALL",
    "name": "Albanian Lek",
    "symbol": "Lek",
    "flag": "ALB",
    "decimal_digits": 0,
    "number": 8,
    "name_plural": "Albanian lekë",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "DZD",
    "name": "Algerian dinar",
    "symbol": "دج",
    "flag": "DZ",
    "decimal_digits": 2,
    "number": 012,
    "name_plural": "Algerian dinars",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "AOA",
    "name": "Angolan Kwanza",
    "symbol": "Kz",
    "flag": "AO",
    "decimal_digits": 2,
    "number": 973,
    "name_plural": "Angolan kwanzas",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true
  },
  {
    "code": "ARS",
    "name": "Argentine Peso",
    "symbol": "\$",
    "flag": "ARS",
    "decimal_digits": 2,
    "number": 32,
    "name_plural": "Argentine pesos",
  },
  {
    "code": "AMD",
    "name": "Armenian Dram",
    "symbol": "֏",
    "flag": "AM",
    "decimal_digits": 0,
    "number": 51,
    "name_plural": "Armenian drams",
  },
  {
    "code": "AZN",
    "name": "Azerbaijani Manat",
    "symbol": "₼",
    "flag": "AZE",
    "decimal_digits": 2,
    "number": 100,
    "name_plural": "Azerbaijani manats",
  },
  {
    "code": "BHD",
    "name": "Bahraini Dinar",
    "symbol": "BD",
    "flag": "BHD",
    "decimal_digits": 3,
    "number": 48,
    "name_plural": "Bahraini dinars",
  },
  {
    "code": "BDT",
    "name": "Bangladeshi Taka",
    "symbol": "৳",
    "flag": "BDT",
    "decimal_digits": 2,
    "number": 50,
    "name_plural": "Bangladeshi takas",
  },
  {
    "code": "BBD",
    "name": "Barbados Dollar",
    "symbol": "\$",
    "flag": "BBD",
    "decimal_digits": 2,
    "number": 52,
    "name_plural": "Barbados dollars",
  },
  {
    "code": "BYN",
    "name": "Belarussian Ruble",
    "symbol": "Br",
    "flag": "BY",
    "decimal_digits": 2,
    "number": 933,
    "name_plural": "Belarusian rubles",
  },
  {
    "code": "BZD",
    "name": "Belize Dollar",
    "symbol": "BZ\$",
    "flag": "BZD",
    "decimal_digits": 2,
    "number": 84,
    "name_plural": "Belize dollars",
  },
  {
    "code": "BMD",
    "name": "Bermuda Dollar",
    "symbol": "\$",
    "flag": "BMD",
    "decimal_digits": 2,
    "number": 60,
    "name_plural": "Bermuda dollars",
  },
  {
    "code": "BTN",
    "name": "Bhutanese Ngultrum",
    "symbol": "Nu.",
    "flag": "BTN",
    "decimal_digits": 2,
    "number": 64,
    "name_plural": "Bhutanese ngultrums",
  },
  {
    "code": "BOB",
    "name": "Bolivia Bolíviano",
    "symbol": "\$b",
    "flag": "BOB",
    "decimal_digits": 2,
    "number": 68,
    "name_plural": "Bolivian bolivianos",
  },
  {
    "code": "BAM",
    "name": "Bosnia and Herzegovina",
    "symbol": "KM",
    "flag": "BA",
    "decimal_digits": 2,
    "number": 977,
    "name_plural": "Bosnia and Herzegovina convertible marks",
  },
  {
    "code": "BWP",
    "name": "Botswanan Pula",
    "symbol": "P",
    "flag": "BW",
    "decimal_digits": 2,
    "number": 72,
    "name_plural": "Botswanan pulas",
  },
  {
    "code": "BND",
    "name": "Brunei Darussalam Dollar",
    "symbol": "\$",
    "flag": "BND",
    "decimal_digits": 2,
    "number": 96,
    "name_plural": "Brunei dollars",
  },
  {
    "code": "BGN",
    "name": "Bulgarian Lev",
    "symbol": "лв",
    "flag": "BGN",
    "decimal_digits": 2,
    "number": 975,
    "name_plural": "Bulgarian leva",
  },
  {
    "code": "BIF",
    "name": "Burundian Franc",
    "symbol": "FBu",
    "flag": "BI",
    "decimal_digits": 2,
    "number": 108,
    "name_plural": "Burundian Franc",
  },
  {
    "code": "KHR",
    "name": "Cambodian riel",
    "symbol": "៛",
    "flag": "KHM",
    "decimal_digits": 2,
    "number": 116,
    "name_plural": "Cambodian riels",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "KYD",
    "name": "Cayman Islands Dollar",
    "symbol": "\$",
    "flag": "KYD",
    "decimal_digits": 2,
    "number": 136,
    "name_plural": "Cayman islands dollars",
  },
  {
    "code": "XAF",
    "name": "Central African CFA franc",
    "symbol": "FCFA",
    "flag": "CFA",
    "decimal_digits": 2,
    "number": 950,
    "name_plural": "Central African CFA francs",
  },
  // {
  //   "code": "XOF",
  //   "name": "UEMOA CFA franc",
  //   "symbol": "FCFA",
  //   "flag": "xof.png",
  //   "decimal_digits": 2,
  //   "number": 960,
  //   "name_plural": "UEMOA CFA francs",
  // },
  {
    "code": "CDF",
    "name": "Congolese franc",
    "symbol": "FC",
    "flag": "CD",
    "decimal_digits": 2,
    "number": 976,
    "name_plural": "Congolese francs",
  },
  {
    "code": "CRC",
    "name": "Costa Rica Colon",
    "symbol": "₡",
    "flag": "CRC",
    "decimal_digits": 0,
    "number": 188,
    "name_plural": "Costa Rican colóns",
  },
  {
    "code": "CUP",
    "name": "Cuban Peso",
    "symbol": "\$MN",
    "flag": "CU",
    "decimal_digits": 2,
    "number": 192,
    "name_plural": "Cuban pesos",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true
  },
  {
    "code": "DOP",
    "name": "Dominican Republic Peso",
    "symbol": "RD\$",
    "flag": "DOP",
    "decimal_digits": 2,
    "number": 214,
    "name_plural": "Dominican pesos",
  },
  {
    "code": "EGP",
    "name": "Egypt Pound",
    "symbol": "£",
    "flag": "EGP",
    "decimal_digits": 2,
    "number": 818,
    "name_plural": "Egyptian pounds",
  },
  {
    "code": "ETB",
    "name": "Ethiopian Birr",
    "symbol": "Br",
    "flag": "ETB",
    "decimal_digits": 2,
    "number": 230,
    "name_plural": "Ethiopian birrs",
  },
  {
    "code": "GMD",
    "name": "Gambian dalasi",
    "symbol": "D",
    "flag": "GMD",
    "decimal_digits": 2,
    "number": 270,
    "name_plural": "Gambian dalasis",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "GEL",
    "name": "Georgian Lari",
    "symbol": "₾",
    "flag": "GEL",
    "decimal_digits": 2,
    "number": 981,
    "name_plural": "Georgian laris",
  },
  {
    "code": "GHS",
    "name": "Ghana Cedi",
    "symbol": "₵",
    "flag": "GHS",
    "decimal_digits": 2,
    "number": 936,
    "name_plural": "Ghanaian cedis",
  },
  {
    "code": "GTQ",
    "name": "Guatemalan quetzal",
    "symbol": "Q",
    "flag": "GT",
    "decimal_digits": 2,
    "number": 320,
    "name_plural": "Guatemalan quetzales",
  },
  {
    "code": "GNF",
    "name": "Guinean Franc",
    "symbol": "FG",
    "flag": "GNF",
    "decimal_digits": 2,
    "number": 324,
    "name_plural": "Guinean Francs",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true
  },
  {
    "code": "GYD",
    "name": "Guyana Dollar",
    "symbol": "\$",
    "flag": "GYD",
    "decimal_digits": 2,
    "number": 328,
    "name_plural": "Guyana dollars",
  },
  {
    "code": "HTG",
    "name": "Haitian gourde",
    "symbol": "G",
    "flag": "HTI",
    "decimal_digits": 2,
    "number": 332,
    "name_plural": "Haitian gourdes",
  },
  {
    "code": "ISK",
    "name": "Iceland Krona",
    "symbol": "kr",
    "flag": "ISK",
    "decimal_digits": 0,
    "number": 352,
    "name_plural": "Icelandic krónur",
  },
  {
    "code": "IQD",
    "name": "Iraqi Dinar",
    "symbol": "د.ع",
    "flag": "IQD",
    "decimal_digits": 3,
    "number": 368,
    "name_plural": "Iraqi dinars",
  },
  {
    "code": "JMD",
    "name": "Jamaica Dollar",
    "symbol": "J\$",
    "flag": "JMD",
    "decimal_digits": 2,
    "number": 388,
    "name_plural": "Jamaican dollars",
  },
  {
    "code": "JOD",
    "name": "Jordanian dinar",
    "symbol": "د.أ",
    "flag": "JO",
    "decimal_digits": 3,
    "number": 400,
    "name_plural": "Jordanian dinars",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "KZT",
    "name": "Kazakhstan Tenge",
    "symbol": "〒",
    "flag": "KZT",
    "decimal_digits": 2,
    "number": 398,
    "name_plural": "Kazakhstani tenges",
  },
  {
    "code": "KES",
    "name": "Kenyan Shilling",
    "symbol": "KSh",
    "flag": "KES",
    "decimal_digits": 2,
    "number": 404,
    "name_plural": "Kenyan shillings",
  },
  {
    "code": "KWD",
    "name": "Kuwaiti Dinar",
    "symbol": "د.ك",
    "flag": "KWD",
    "decimal_digits": 3,
    "number": 414,
    "name_plural": "Kuwaiti dinars",
  },
  {
    "code": "KGS",
    "name": "Kyrgyzstani som",
    "symbol": "с",
    "flag": "KG",
    "decimal_digits": 2,
    "number": 417,
    "name_plural": "Kyrgyzstani som",
  },
  {
    "code": "LAK",
    "name": "Laos Kip",
    "symbol": "₭",
    "flag": "LAK",
    "decimal_digits": 2,
    "number": 418,
    "name_plural": "Laos Kip",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "LBP",
    "name": "Lebanese Pound",
    "symbol": "ل.ل",
    "flag": "LB",
    "decimal_digits": 2,
    "number": 422,
    "name_plural": "Lebanese pounds",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true
  },
  {
    "code": "LRD",
    "name": "Liberia Dollar",
    "symbol": "\$",
    "flag": "LRD",
    "decimal_digits": 2,
    "number": 430,
    "name_plural": "Liberia dollars",
  },
  {
    "code": "MKD",
    "name": "Macedonia Denar",
    "symbol": "ден",
    "flag": "MKD",
    "decimal_digits": 2,
    "number": 807,
    "name_plural": "Macedonian denari",
  },
  {
    "code": "MGA",
    "name": "Malagasy Ariary",
    "symbol": "Ar",
    "flag": "MG",
    "decimal_digits": 0,
    "number": 969,
    "name_plural": "Malagasy ariaries",
  },
  {
    "code": "MWK",
    "name": "Malawian Kwacha",
    "symbol": "MK",
    "flag": "MWK",
    "decimal_digits": 2,
    "number": 454,
    "name_plural": "Malawian kwachas",
  },
  {
    "code": "MVR",
    "name": "Maldivian Rufiyaa",
    "symbol": "/-",
    "flag": "MV",
    "decimal_digits": 2,
    "number": 462,
    "name_plural": "Maldivian Rufiyaa",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "MUR",
    "name": "Mauritius Rupee",
    "symbol": "₨",
    "flag": "MUR",
    "decimal_digits": 0,
    "number": 480,
    "name_plural": "Mauritian rupees",
  },
  {
    "code": "MDL",
    "name": "Moldovan Leu",
    "symbol": "L",
    "flag": "MDL",
    "decimal_digits": 2,
    "number": 498,
    "name_plural": "Moldovan lei",
  },
  {
    "code": "MNT",
    "name": "Mongolia Tughrik",
    "symbol": "₮",
    "flag": "MNT",
    "decimal_digits": 2,
    "number": 496,
    "name_plural": "Mongolia tugriks",
  },
  {
    "code": "MAD",
    "name": "Moroccan Dirham",
    "symbol": "MAD",
    "flag": "MAD",
    "decimal_digits": 2,
    "number": 504,
    "name_plural": "Moroccan dirhams",
  },
  {
    "code": "MZN",
    "name": "Mozambique Metical",
    "symbol": "MT",
    "flag": "MZN",
    "decimal_digits": 2,
    "number": 943,
    "name_plural": "Mozambican meticals",
  },
  {
    "code": "MMK",
    "name": "Myanmar Kyat",
    "symbol": "Ks",
    "flag": "MM",
    "decimal_digits": 2,
    "number": 104,
    "name_plural": "Myanmar Kyats",
  },
  {
    "code": "NAD",
    "name": "Namibia Dollar",
    "symbol": "\$",
    "flag": "NAD",
    "decimal_digits": 2,
    "number": 516,
    "name_plural": "Namibian dollars",
  },
  {
    "code": "NPR",
    "name": "Nepal Rupee",
    "symbol": "₨",
    "flag": "NPR",
    "decimal_digits": 2,
    "number": 524,
    "name_plural": "Nepalese rupees",
  },
  {
    "code": "NIO",
    "name": "Nicaragua Cordoba",
    "symbol": "C\$",
    "flag": "NIO",
    "decimal_digits": 2,
    "number": 558,
    "name_plural": "Nicaraguan córdobas",
  },
  {
    "code": "NGN",
    "name": "Nigeria Naira",
    "symbol": "₦",
    "flag": "NGN",
    "decimal_digits": 2,
    "number": 566,
    "name_plural": "Nigerian nairas",
  },
  {
    "code": "OMR",
    "name": "Oman Rial",
    "symbol": "﷼",
    "flag": "OMR",
    "decimal_digits": 3,
    "number": 512,
    "name_plural": "Omani rials",
  },
  {
    "code": "PKR",
    "name": "Pakistan Rupee",
    "symbol": "₨",
    "flag": "PKR",
    "decimal_digits": 0,
    "number": 586,
    "name_plural": "Pakistani rupees",
  },
  {
    "code": "PGK",
    "name": "Papua New Guinean Kina",
    "symbol": "K",
    "flag": "PGK",
    "decimal_digits": 2,
    "number": 598,
    "name_plural": "Papua New Guinean Kina",
  },
  {
    "code": "PYG",
    "name": "Paraguay Guarani",
    "symbol": "₲",
    "flag": "PYG",
    "decimal_digits": 0,
    "number": 600,
    "name_plural": "Paraguayan guaranis",
  },
  {
    "code": "PEN",
    "name": "Peru Sol",
    "symbol": "S/.",
    "flag": "PEN",
    "decimal_digits": 2,
    "number": 604,
    "name_plural": "Peruvian nuevos soles",
  },
  {
    "code": "QAR",
    "name": "Qatar Riyal",
    "symbol": "﷼",
    "flag": "QAR",
    "decimal_digits": 2,
    "number": 634,
    "name_plural": "Qatari rials",
  },
  {
    "code": "RWF",
    "name": "Rwandan franc",
    "symbol": "FRw",
    "flag": "RWA",
    "decimal_digits": 0,
    "number": 646,
    "name_plural": "Rwandan francs",
  },
  {
    "code": "RSD",
    "name": "Serbia Dinar",
    "symbol": "Дин.",
    "flag": "RSD",
    "decimal_digits": 0,
    "number": 941,
    "name_plural": "Serbian dinars",
  },
  {
    "code": "SCR",
    "name": "Seychellois rupee",
    "symbol": "₨",
    "flag": "SC",
    "decimal_digits": 2,
    "number": 690,
    "name_plural": "Seychelles rupee",
  },
  {
    "code": "SOS",
    "name": "Somalia Shilling",
    "symbol": "S",
    "flag": "SOS",
    "decimal_digits": 0,
    "number": 706,
    "name_plural": "Somali shillings",
  },
  {
    "code": "LKR",
    "name": "Sri Lanka Rupee",
    "symbol": "₨",
    "flag": "LKR",
    "decimal_digits": 2,
    "number": 144,
    "name_plural": "Sri Lankan rupees",
  },
  {
    "code": "SRD",
    "name": "Suriname Dollar",
    "symbol": "\$",
    "flag": "SRD",
    "decimal_digits": 2,
    "number": 968,
    "name_plural": "Suriname Dollars",
  },
  {
    "code": "SYP",
    "name": "Syrian Lira",
    "symbol": "LS",
    "flag": "SYP",
    "decimal_digits": 2,
    "number": 760,
    "name_plural": "Syrian lira",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "TZS",
    "name": "Tanzanian Shilling",
    "symbol": "TSh",
    "flag": "TZS",
    "decimal_digits": 0,
    "number": 834,
    "name_plural": "Tanzanian shillings",
  },
  {
    "code": "TOP",
    "name": "Tongan Pa'anga",
    "symbol": "T\$",
    "flag": "TO",
    "decimal_digits": 2,
    "number": 776,
    "name_plural": "Tongan pa'angas",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true
  },
  {
    "code": "TTD",
    "name": "Trinidad and Tobago Dollar",
    "symbol": "TT\$",
    "flag": "TTD",
    "decimal_digits": 2,
    "number": 780,
    "name_plural": "Trinidad and Tobago dollars",
  },
  {
    "code": "TND",
    "name": "Tunisian dinar",
    "symbol": "د.ت",
    "flag": "TN",
    "decimal_digits": 3,
    "number": 788,
    "name_plural": "Tunisian dinars",
  },
  {
    "code": "UGX",
    "name": "Ugandan Shilling",
    "symbol": "USh",
    "flag": "UGX",
    "decimal_digits": 0,
    "number": 800,
    "name_plural": "Ugandan shillings",
  },
  {
    "code": "UAH",
    "name": "Ukraine Hryvnia",
    "symbol": "₴",
    "flag": "UAH",
    "decimal_digits": 2,
    "number": 980,
    "name_plural": "Ukrainian hryvnias",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "UZS",
    "name": "Uzbekistani Sum",
    "symbol": "UZS",
    "flag": "UZ",
    "decimal_digits": 2,
    "number": 860,
    "name_plural": "Uzbekistani Sums",
  },
  {
    "code": "UYU",
    "name": "Uruguay Peso",
    "symbol": "\$U",
    "flag": "UYU",
    "decimal_digits": 2,
    "number": 858,
    "name_plural": "Uruguayan pesos",
  },
  {
    "code": "VEF",
    "name": "Venezuela Bolívar",
    "symbol": "Bs",
    "flag": "VEF",
    "decimal_digits": 2,
    "number": 937,
    "name_plural": "Venezuelan bolívars",
  },
  {
    "code": "VND",
    "name": "Vietnamese Dong",
    "symbol": "₫",
    "flag": "VND",
    "decimal_digits": 0,
    "number": 704,
    "name_plural": "Vietnamese dong",
  },
  {
    "code": "YER",
    "name": "Yemen Rial",
    "symbol": "﷼",
    "flag": "YER",
    "decimal_digits": 2,
    "number": 886,
    "name_plural": "Yemeni rials",
  },
  {
    "code": "ZMW",
    "name": "Zambian kwacha",
    "symbol": "ZK",
    "flag": "ZM",
    "decimal_digits": 2,
    "number": 967,
    "name_plural": "Zambian kwachas",
  },
  {
    "code": "ZWL",
    "name": "Zimbabwean Dollar",
    "symbol": "\$ZWL",
    "flag": "ZW",
    "decimal_digits": 2,
    "number": 932,
    "name_plural": "Zimbabwean dollars",
  },
  {
    "code": "IRR",
    "name": "Iranian rial",
    "symbol": "﷼",
    "flag": "IR",
    "decimal_digits": 2,
    "number": 364,
    "name_plural": "Iranian rials",
  },
  {
    "code": "LYD",
    "name": "Libyan dinar",
    "symbol": "ل.د",
    "flag": "LY",
    "decimal_digits": 3,
    "number": 434,
    "name_plural": "Libyan dinars",
  },
  {
    "code": "TJS",
    "name": "Tajikistani somoni",
    "symbol": "SM",
    "flag": "TJ",
    "decimal_digits": 2,
    "number": 972,
    "name_plural": "Tajikistani somonis",
  },
  {
    "code": "TMT",
    "name": "Turkmenistani manat",
    "symbol": "m",
    "flag": "TM",
    "decimal_digits": 2,
    "number": 934,
    "name_plural": "Turkmenistani manat",
  },
];